language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

dist: xenial

jdk:
  - openjdk8

sudo: false

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt ++${TRAVIS_SCALA_VERSION} test runTests
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
