language: scala

scala:
  - 2.12.11
  - 2.13.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

dist: xenial

jdk:
  - openjdk8

sudo: false

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt ++${TRAVIS_SCALA_VERSION} scalafmtCheck scalafmtSbtCheck test:scalafmtCheck test runTests
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
